// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5jSGN_1taWPcAk6k8w2ClOYH0GY5SKAs',
    appId: '1:839973994534:web:9f1b711856a20ed9e226e7',
    messagingSenderId: '839973994534',
    projectId: 'chat-app-6e490',
    authDomain: 'chat-app-6e490.firebaseapp.com',
    storageBucket: 'chat-app-6e490.appspot.com',
    measurementId: 'G-9JLHBD999Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq99Xj_c1179N62782uz7d7WcIa4gYbq0',
    appId: '1:839973994534:android:6a0ad58b044a67bde226e7',
    messagingSenderId: '839973994534',
    projectId: 'chat-app-6e490',
    storageBucket: 'chat-app-6e490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSnBJsaLxMRmR4r9zA4wzYSETguIABqZU',
    appId: '1:839973994534:ios:3489af81d5097aa8e226e7',
    messagingSenderId: '839973994534',
    projectId: 'chat-app-6e490',
    storageBucket: 'chat-app-6e490.appspot.com',
    iosClientId: '839973994534-dt7b1fb5s6ds265jiplfihdm0apq319e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSnBJsaLxMRmR4r9zA4wzYSETguIABqZU',
    appId: '1:839973994534:ios:3489af81d5097aa8e226e7',
    messagingSenderId: '839973994534',
    projectId: 'chat-app-6e490',
    storageBucket: 'chat-app-6e490.appspot.com',
    iosClientId: '839973994534-dt7b1fb5s6ds265jiplfihdm0apq319e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );
}
